# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 10143
  start_block: 0
  contracts:
  - name: SmartPortfolio
    address:
    - 0x065A0af7bfF900deB2Bcb7Ae3fc6e1dD52579aC7
    handler: src/EventHandlers.ts
    events:
    - event: ApprovalRevoked(address indexed user, address indexed token)
    - event: DynamicAllocationSet(address indexed user, address[] tokens, uint16[] percents)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: Paused(address indexed by)
    - event: RebalanceExecuted(address indexed user, address indexed executor, address tokenIn, address tokenOut, uint256 amountIn, uint256 amountOut, string reason, uint256 timestamp)
    - event: Unpaused(address indexed by)
unordered_multichain_mode: true
preload_handlers: true
